import type { Machine, Alert, MaintenanceRecord, Dataset, ModelVersion, ModelEvaluation, SensorReading } from '../types';

export const INITIAL_MACHINES: Machine[] = [
  {
    id: 'm-fd001-03',
    machineCode: 'FD001-ENG-003',
    name: 'Turbofan Unit #3 (Severe Drift)',
    machineType: 'Turbofan engine (simulated)',
    location: 'Test Stand Delta (Simulated)',
    installDate: '2024-01-15',
    operationalStatus: 'active',
    healthIndicator: 34,
    healthBand: 'Poor',
    healthComponents: {
      failureRiskPenalty: 41, // 50 * 0.82
      anomalyPenalty: 21,     // 30 * 0.70
      trendPenalty: 14,       // 20 * 0.70
      otherPenalty: 0,
    },
    failureProbability: 0.82,
    predictionHorizon: 30,
    riskLevel: 'Critical',
    currentCycle: 198,
    anomalySeverity: 0.70,
    anomalyScore: 0.84,
    anomalyStatus: 'anomaly',
    reliabilityStatus: 'ok',
    datasetBadge: 'NASA C-MAPSS FD001',
    lastUpdated: 'Cycle 198',
    explanation: {
      headline: 'Failure probability is 82% within the next 30 cycles mainly because sensor_11 and sensor_9 drifted significantly upward.',
      topContributingFeatures: [
        { feature: 'sensor_11', direction: 'raises', weight: 0.38, value: 48.12, baselineRef: '47.05 - 47.45' },
        { feature: 'sensor_9', direction: 'raises', weight: 0.29, value: 9098.4, baselineRef: '9045.0 - 9068.0' },
        { feature: 'sensor_14', direction: 'raises', weight: 0.18, value: 8180.2, baselineRef: '8120.0 - 8145.0' },
        { feature: 'sensor_4', direction: 'raises', weight: 0.12, value: 1422.6, baselineRef: '1398.0 - 1410.0' },
        { feature: 'sensor_2', direction: 'lowers', weight: -0.05, value: 642.1, baselineRef: '641.5 - 643.0' },
      ],
      trendFacts: [
        'sensor_11 changed by +2.1% over the last 20 cycles and is outside its healthy range (3.2 robust-z above baseline).',
        'sensor_9 changed by +1.8% over the last 20 cycles with steepening positive slope.',
        'High anomaly severity of 0.70 detected across 8 consecutive cycles.',
      ],
      summaryText: 'Calibrated failure probability of 82% within horizon H=30. Multiple thermodynamic sensor readings show sustained divergence from the training healthy reference distribution.',
    },
    recommendation: {
      ruleId: 'RULE-PdM-CRIT-01',
      text: 'Schedule immediate inspection of this unit and review flagged sensors: sensor_11, sensor_9, sensor_14. Verify operational integrity before proceeding with further cycles.',
      priority: 'urgent',
      rationale: 'Calibrated failure probability >= 0.80 and severe anomaly episode ongoing for >= 5 cycles.',
    },
    lineage: {
      machineCode: 'FD001-ENG-003',
      datasetName: 'NASA C-MAPSS FD001',
      datasetVersion: 'v1.0-FD001-standard',
      schemaMappingHash: 'a89f3c42be7e1b54',
      featureConfigVersion: 'fc-v2.1-cmapss',
      preprocessingVersion: 'prep-v1.4-robust-scaler',
      failureModelVersion: 'LightGBM-FD001-v1.2',
      anomalyModelVersion: 'IsolationForest-FD001-v1.0',
      predictionHorizon: 30,
      predictionHorizonUnit: 'cycles',
      asOfCycle: 198,
      predictedAt: '2026-09-30 18:45:00 UTC',
      inputWindowLength: 30,
    },
  },
  {
    id: 'm-fd001-02',
    machineCode: 'FD001-ENG-002',
    name: 'Turbofan Unit #2 (Early Degradation)',
    machineType: 'Turbofan engine (simulated)',
    location: 'Test Stand Bravo (Simulated)',
    installDate: '2024-02-01',
    operationalStatus: 'active',
    healthIndicator: 64,
    healthBand: 'Warning',
    healthComponents: {
      failureRiskPenalty: 21, // 50 * 0.42
      anomalyPenalty: 9,      // 30 * 0.30
      trendPenalty: 6,        // 20 * 0.30
      otherPenalty: 0,
    },
    failureProbability: 0.42,
    predictionHorizon: 30,
    riskLevel: 'Medium',
    currentCycle: 142,
    anomalySeverity: 0.30,
    anomalyScore: 0.46,
    anomalyStatus: 'warning',
    reliabilityStatus: 'ok',
    datasetBadge: 'NASA C-MAPSS FD001',
    lastUpdated: 'Cycle 142',
    explanation: {
      headline: 'Failure probability is 42% within the next 30 cycles; mild upward drift detected on sensor_11 and sensor_4.',
      topContributingFeatures: [
        { feature: 'sensor_11', direction: 'raises', weight: 0.24, value: 47.65, baselineRef: '47.05 - 47.45' },
        { feature: 'sensor_4', direction: 'raises', weight: 0.18, value: 1412.3, baselineRef: '1398.0 - 1410.0' },
        { feature: 'sensor_12', direction: 'lowers', weight: -0.11, value: 521.8, baselineRef: '521.0 - 522.5' },
      ],
      trendFacts: [
        'sensor_11 increased by +0.8% over the past 20 cycles.',
        'No sustained anomaly episode yet; intermittent boundary excursions observed.',
      ],
      summaryText: 'Failure risk is in the Medium band. Health indicator shows gradual decline consistent with mid-life simulated wear.',
    },
    recommendation: {
      ruleId: 'RULE-PdM-WARN-02',
      text: 'Increase monitoring frequency and review recent operating settings for this unit. Track sensor_11 trajectory closely.',
      priority: 'medium',
      rationale: 'Failure probability in medium band (0.20 - 0.50) with emerging baseline drift.',
    },
    lineage: {
      machineCode: 'FD001-ENG-002',
      datasetName: 'NASA C-MAPSS FD001',
      datasetVersion: 'v1.0-FD001-standard',
      schemaMappingHash: 'a89f3c42be7e1b54',
      featureConfigVersion: 'fc-v2.1-cmapss',
      preprocessingVersion: 'prep-v1.4-robust-scaler',
      failureModelVersion: 'LightGBM-FD001-v1.2',
      anomalyModelVersion: 'IsolationForest-FD001-v1.0',
      predictionHorizon: 30,
      predictionHorizonUnit: 'cycles',
      asOfCycle: 142,
      predictedAt: '2026-09-30 18:40:00 UTC',
      inputWindowLength: 30,
    },
  },
  {
    id: 'm-fd001-01',
    machineCode: 'FD001-ENG-001',
    name: 'Turbofan Unit #1 (Baseline Healthy)',
    machineType: 'Turbofan engine (simulated)',
    location: 'Test Stand Alpha (Simulated)',
    installDate: '2024-03-10',
    operationalStatus: 'active',
    healthIndicator: 94,
    healthBand: 'Excellent',
    healthComponents: {
      failureRiskPenalty: 3,  // 50 * 0.06
      anomalyPenalty: 2,      // 30 * 0.07
      trendPenalty: 1,        // 20 * 0.05
      otherPenalty: 0,
    },
    failureProbability: 0.06,
    predictionHorizon: 30,
    riskLevel: 'Low',
    currentCycle: 76,
    anomalySeverity: 0.05,
    anomalyScore: 0.12,
    anomalyStatus: 'normal',
    reliabilityStatus: 'ok',
    datasetBadge: 'NASA C-MAPSS FD001',
    lastUpdated: 'Cycle 76',
    explanation: {
      headline: 'Failure probability is 6% within the next 30 cycles; all sensor channels operate well within normal baseline tolerances.',
      topContributingFeatures: [
        { feature: 'sensor_11', direction: 'lowers', weight: -0.22, value: 47.18, baselineRef: '47.05 - 47.45' },
        { feature: 'sensor_9', direction: 'lowers', weight: -0.19, value: 9052.1, baselineRef: '9045.0 - 9068.0' },
        { feature: 'sensor_12', direction: 'lowers', weight: -0.15, value: 522.0, baselineRef: '521.0 - 522.5' },
      ],
      trendFacts: [
        'sensor_11 and sensor_9 variance is within 0.3 robust-z of healthy training baseline.',
        'Zero anomaly flags triggered in the past 50 cycles.',
      ],
      summaryText: 'All operational parameters reflect nominal simulated turbofan performance.',
    },
    recommendation: {
      ruleId: 'RULE-PdM-OK-01',
      text: 'Continue normal monitoring schedule. No maintenance intervention required.',
      priority: 'low',
      rationale: 'Health indicator > 85, calibrated failure probability < 0.10.',
    },
    lineage: {
      machineCode: 'FD001-ENG-001',
      datasetName: 'NASA C-MAPSS FD001',
      datasetVersion: 'v1.0-FD001-standard',
      schemaMappingHash: 'a89f3c42be7e1b54',
      featureConfigVersion: 'fc-v2.1-cmapss',
      preprocessingVersion: 'prep-v1.4-robust-scaler',
      failureModelVersion: 'LightGBM-FD001-v1.2',
      anomalyModelVersion: 'IsolationForest-FD001-v1.0',
      predictionHorizon: 30,
      predictionHorizonUnit: 'cycles',
      asOfCycle: 76,
      predictedAt: '2026-09-30 18:30:00 UTC',
      inputWindowLength: 30,
    },
  },
  {
    id: 'm-fd001-04',
    machineCode: 'FD001-ENG-004',
    name: 'Turbofan Unit #4 (Stable Mid-Run)',
    machineType: 'Turbofan engine (simulated)',
    location: 'Test Stand Alpha (Simulated)',
    installDate: '2024-02-12',
    operationalStatus: 'active',
    healthIndicator: 88,
    healthBand: 'Healthy',
    healthComponents: { failureRiskPenalty: 6, anomalyPenalty: 4, trendPenalty: 2, otherPenalty: 0 },
    failureProbability: 0.12,
    predictionHorizon: 30,
    riskLevel: 'Low',
    currentCycle: 92,
    anomalySeverity: 0.08,
    anomalyScore: 0.18,
    anomalyStatus: 'normal',
    reliabilityStatus: 'ok',
    datasetBadge: 'NASA C-MAPSS FD001',
    lastUpdated: 'Cycle 92',
    explanation: {
      headline: 'Low failure probability (12%) within next 30 cycles; standard operating variances.',
      topContributingFeatures: [
        { feature: 'sensor_11', direction: 'lowers', weight: -0.16, value: 47.24, baselineRef: '47.05 - 47.45' },
      ],
      trendFacts: ['Operating within healthy reference bounds.'],
      summaryText: 'Healthy performance across all 21 sensor channels.',
    },
    recommendation: {
      ruleId: 'RULE-PdM-OK-01',
      text: 'Continue normal monitoring schedule.',
      priority: 'low',
      rationale: 'Health indicator 88, failure probability in low band.',
    },
    lineage: {
      machineCode: 'FD001-ENG-004',
      datasetName: 'NASA C-MAPSS FD001',
      datasetVersion: 'v1.0-FD001-standard',
      schemaMappingHash: 'a89f3c42be7e1b54',
      featureConfigVersion: 'fc-v2.1-cmapss',
      preprocessingVersion: 'prep-v1.4-robust-scaler',
      failureModelVersion: 'LightGBM-FD001-v1.2',
      anomalyModelVersion: 'IsolationForest-FD001-v1.0',
      predictionHorizon: 30,
      predictionHorizonUnit: 'cycles',
      asOfCycle: 92,
      predictedAt: '2026-09-30 18:25:00 UTC',
      inputWindowLength: 30,
    },
  },
  {
    id: 'm-fd001-05',
    machineCode: 'FD001-ENG-005',
    name: 'Turbofan Unit #5 (Sensor Shift)',
    machineType: 'Turbofan engine (simulated)',
    location: 'Test Stand Gamma (Simulated)',
    installDate: '2024-01-20',
    operationalStatus: 'active',
    healthIndicator: 58,
    healthBand: 'Warning',
    healthComponents: { failureRiskPenalty: 24, anomalyPenalty: 12, trendPenalty: 6, otherPenalty: 0 },
    failureProbability: 0.48,
    predictionHorizon: 30,
    riskLevel: 'Medium',
    currentCycle: 155,
    anomalySeverity: 0.38,
    anomalyScore: 0.52,
    anomalyStatus: 'warning',
    reliabilityStatus: 'reduced',
    reliabilityWarningReason: 'sensor_14 median lies outside training p1-p99 reference interval.',
    datasetBadge: 'NASA C-MAPSS FD001',
    lastUpdated: 'Cycle 155',
    explanation: {
      headline: 'Medium failure probability (48%) with reduced prediction reliability warning.',
      topContributingFeatures: [
        { feature: 'sensor_14', direction: 'raises', weight: 0.32, value: 8165.0, baselineRef: '8120.0 - 8145.0' },
        { feature: 'sensor_11', direction: 'raises', weight: 0.22, value: 47.78, baselineRef: '47.05 - 47.45' },
      ],
      trendFacts: ['sensor_14 shows noticeable shift compared to training distribution.'],
      summaryText: 'Prediction reliability is marked reduced because input sensor distribution exhibits out-of-range deviations.',
    },
    recommendation: {
      ruleId: 'RULE-PdM-WARN-03',
      text: 'Inspect sensor calibration on sensor_14 and cross-check operating context.',
      priority: 'medium',
      rationale: 'Reduced prediction reliability flag active; input data differs from training reference.',
    },
    lineage: {
      machineCode: 'FD001-ENG-005',
      datasetName: 'NASA C-MAPSS FD001',
      datasetVersion: 'v1.0-FD001-standard',
      schemaMappingHash: 'a89f3c42be7e1b54',
      featureConfigVersion: 'fc-v2.1-cmapss',
      preprocessingVersion: 'prep-v1.4-robust-scaler',
      failureModelVersion: 'LightGBM-FD001-v1.2',
      anomalyModelVersion: 'IsolationForest-FD001-v1.0',
      predictionHorizon: 30,
      predictionHorizonUnit: 'cycles',
      asOfCycle: 155,
      predictedAt: '2026-09-30 18:20:00 UTC',
      inputWindowLength: 30,
    },
  },
  {
    id: 'm-fd001-06',
    machineCode: 'FD001-ENG-006',
    name: 'Turbofan Unit #6 (Under Maintenance)',
    machineType: 'Turbofan engine (simulated)',
    location: 'Hangar Bay 2 (Simulated)',
    installDate: '2023-11-05',
    operationalStatus: 'maintenance',
    healthIndicator: 45,
    healthBand: 'Poor',
    healthComponents: { failureRiskPenalty: 33, anomalyPenalty: 15, trendPenalty: 7, otherPenalty: 0 },
    failureProbability: 0.66,
    predictionHorizon: 30,
    riskLevel: 'High',
    currentCycle: 178,
    anomalySeverity: 0.52,
    anomalyScore: 0.68,
    anomalyStatus: 'anomaly',
    reliabilityStatus: 'ok',
    datasetBadge: 'NASA C-MAPSS FD001',
    lastUpdated: 'Cycle 178',
    explanation: {
      headline: 'High failure probability (66%); maintenance work currently in progress.',
      topContributingFeatures: [
        { feature: 'sensor_11', direction: 'raises', weight: 0.35, value: 47.95, baselineRef: '47.05 - 47.45' },
        { feature: 'sensor_9', direction: 'raises', weight: 0.28, value: 9082.0, baselineRef: '9045.0 - 9068.0' },
      ],
      trendFacts: ['Inspection initiated by engineer following high-risk alert.'],
      summaryText: 'Machine operational status set to maintenance during ongoing teardown and inspection.',
    },
    recommendation: {
      ruleId: 'RULE-PdM-CRIT-02',
      text: 'Complete physical inspection and record maintenance outcome before returning to active status.',
      priority: 'high',
      rationale: 'Active maintenance record in progress.',
    },
    lineage: {
      machineCode: 'FD001-ENG-006',
      datasetName: 'NASA C-MAPSS FD001',
      datasetVersion: 'v1.0-FD001-standard',
      schemaMappingHash: 'a89f3c42be7e1b54',
      featureConfigVersion: 'fc-v2.1-cmapss',
      preprocessingVersion: 'prep-v1.4-robust-scaler',
      failureModelVersion: 'LightGBM-FD001-v1.2',
      anomalyModelVersion: 'IsolationForest-FD001-v1.0',
      predictionHorizon: 30,
      predictionHorizonUnit: 'cycles',
      asOfCycle: 178,
      predictedAt: '2026-09-30 18:15:00 UTC',
      inputWindowLength: 30,
    },
  },
  {
    id: 'm-fd001-07',
    machineCode: 'FD001-ENG-007',
    name: 'Turbofan Unit #7 (Healthy Fleet)',
    machineType: 'Turbofan engine (simulated)',
    location: 'Test Stand Bravo (Simulated)',
    installDate: '2024-03-01',
    operationalStatus: 'active',
    healthIndicator: 91,
    healthBand: 'Excellent',
    healthComponents: { failureRiskPenalty: 4, anomalyPenalty: 3, trendPenalty: 2, otherPenalty: 0 },
    failureProbability: 0.08,
    predictionHorizon: 30,
    riskLevel: 'Low',
    currentCycle: 85,
    anomalySeverity: 0.06,
    anomalyScore: 0.15,
    anomalyStatus: 'normal',
    reliabilityStatus: 'ok',
    datasetBadge: 'NASA C-MAPSS FD001',
    lastUpdated: 'Cycle 85',
    explanation: {
      headline: 'Low risk of failure (8%); steady sensor stability across runs.',
      topContributingFeatures: [
        { feature: 'sensor_11', direction: 'lowers', weight: -0.20, value: 47.16, baselineRef: '47.05 - 47.45' },
      ],
      trendFacts: ['Zero abnormal readings detected.'],
      summaryText: 'Excellent condition with no indicators of degradation.',
    },
    recommendation: {
      ruleId: 'RULE-PdM-OK-01',
      text: 'Maintain standard observation protocol.',
      priority: 'low',
      rationale: 'Health indicator 91, low failure probability.',
    },
    lineage: {
      machineCode: 'FD001-ENG-007',
      datasetName: 'NASA C-MAPSS FD001',
      datasetVersion: 'v1.0-FD001-standard',
      schemaMappingHash: 'a89f3c42be7e1b54',
      featureConfigVersion: 'fc-v2.1-cmapss',
      preprocessingVersion: 'prep-v1.4-robust-scaler',
      failureModelVersion: 'LightGBM-FD001-v1.2',
      anomalyModelVersion: 'IsolationForest-FD001-v1.0',
      predictionHorizon: 30,
      predictionHorizonUnit: 'cycles',
      asOfCycle: 85,
      predictedAt: '2026-09-30 18:10:00 UTC',
      inputWindowLength: 30,
    },
  },
  {
    id: 'm-fd001-08',
    machineCode: 'FD001-ENG-008',
    name: 'Turbofan Unit #8 (Moderate Wear)',
    machineType: 'Turbofan engine (simulated)',
    location: 'Test Stand Delta (Simulated)',
    installDate: '2024-01-05',
    operationalStatus: 'active',
    healthIndicator: 73,
    healthBand: 'Healthy',
    healthComponents: { failureRiskPenalty: 14, anomalyPenalty: 8, trendPenalty: 5, otherPenalty: 0 },
    failureProbability: 0.28,
    predictionHorizon: 30,
    riskLevel: 'Medium',
    currentCycle: 124,
    anomalySeverity: 0.22,
    anomalyScore: 0.35,
    anomalyStatus: 'normal',
    reliabilityStatus: 'ok',
    datasetBadge: 'NASA C-MAPSS FD001',
    lastUpdated: 'Cycle 124',
    explanation: {
      headline: 'Failure probability is 28% within horizon H=30; mild thermal cycle accumulation.',
      topContributingFeatures: [
        { feature: 'sensor_11', direction: 'raises', weight: 0.15, value: 47.48, baselineRef: '47.05 - 47.45' },
      ],
      trendFacts: ['Slight upward drift in sensor_11 over the last 15 cycles.'],
      summaryText: 'Healthy overall with normal expected wear trends.',
    },
    recommendation: {
      ruleId: 'RULE-PdM-WARN-01',
      text: 'Routine monitoring at scheduled intervals.',
      priority: 'low',
      rationale: 'Probability within acceptable operational boundary.',
    },
    lineage: {
      machineCode: 'FD001-ENG-008',
      datasetName: 'NASA C-MAPSS FD001',
      datasetVersion: 'v1.0-FD001-standard',
      schemaMappingHash: 'a89f3c42be7e1b54',
      featureConfigVersion: 'fc-v2.1-cmapss',
      preprocessingVersion: 'prep-v1.4-robust-scaler',
      failureModelVersion: 'LightGBM-FD001-v1.2',
      anomalyModelVersion: 'IsolationForest-FD001-v1.0',
      predictionHorizon: 30,
      predictionHorizonUnit: 'cycles',
      asOfCycle: 124,
      predictedAt: '2026-09-30 18:05:00 UTC',
      inputWindowLength: 30,
    },
  },
];

export const INITIAL_ALERTS: Alert[] = [
  {
    id: 'alt-001',
    machineId: 'm-fd001-03',
    machineCode: 'FD001-ENG-003',
    machineName: 'Turbofan Unit #3 (Severe Drift)',
    type: 'high_failure_risk',
    severity: 'critical',
    status: 'open',
    asOfCycle: 198,
    triggeredAt: '2026-09-30 18:45:00 UTC',
    message: 'High failure probability (82%) exceeds critical alert threshold for 6 consecutive cycles.',
    reliabilityStatus: 'ok',
    recommendationText: 'Schedule immediate inspection of this unit and review flagged sensors: sensor_11, sensor_9, sensor_14. Verify operational integrity before proceeding with further cycles.',
    recommendationRuleId: 'RULE-PdM-CRIT-01',
  },
  {
    id: 'alt-002',
    machineId: 'm-fd001-05',
    machineCode: 'FD001-ENG-005',
    machineName: 'Turbofan Unit #5 (Sensor Shift)',
    type: 'severe_anomaly',
    severity: 'medium',
    status: 'acknowledged',
    asOfCycle: 155,
    triggeredAt: '2026-09-30 18:20:00 UTC',
    message: 'Statistical baseline deviation on sensor_14 exceeds 3.5 z-score; prediction reliability marked reduced.',
    reliabilityStatus: 'reduced',
    recommendationText: 'Inspect sensor calibration on sensor_14 and cross-check operating context.',
    recommendationRuleId: 'RULE-PdM-WARN-03',
    acknowledgedBy: 'engineer@demo.internal',
    acknowledgedAt: '2026-09-30 18:35:00 UTC',
  },
  {
    id: 'alt-003',
    machineId: 'm-fd001-06',
    machineCode: 'FD001-ENG-006',
    machineName: 'Turbofan Unit #6 (Under Maintenance)',
    type: 'rapid_deterioration',
    severity: 'high',
    status: 'acknowledged',
    asOfCycle: 178,
    triggeredAt: '2026-09-30 18:15:00 UTC',
    message: 'Machine Health Indicator dropped by 28 points within 15 cycles.',
    reliabilityStatus: 'ok',
    recommendationText: 'Perform borescope inspection and check high-pressure turbine seal clearances.',
    recommendationRuleId: 'RULE-PdM-CRIT-02',
    acknowledgedBy: 'engineer@demo.internal',
    acknowledgedAt: '2026-09-30 18:22:00 UTC',
  },
  {
    id: 'alt-004',
    machineId: 'm-fd001-02',
    machineCode: 'FD001-ENG-002',
    machineName: 'Turbofan Unit #2 (Early Degradation)',
    type: 'high_failure_risk',
    severity: 'medium',
    status: 'resolved',
    asOfCycle: 140,
    triggeredAt: '2026-09-29 11:30:00 UTC',
    message: 'Failure probability crossed medium risk band (42%).',
    reliabilityStatus: 'ok',
    recommendationText: 'Increase monitoring frequency and review recent operating settings for this unit.',
    recommendationRuleId: 'RULE-PdM-WARN-02',
    acknowledgedBy: 'engineer@demo.internal',
    acknowledgedAt: '2026-09-29 11:45:00 UTC',
    resolvedBy: 'engineer@demo.internal',
    resolvedAt: '2026-09-29 14:10:00 UTC',
    resolutionType: 'no_action_needed',
    resolutionNote: 'Inspected sensor connections. Drift within tolerated simulation limits. Monitoring heightened.',
  },
];

export const INITIAL_MAINTENANCE_RECORDS: MaintenanceRecord[] = [
  {
    id: 'maint-001',
    machineId: 'm-fd001-06',
    machineCode: 'FD001-ENG-006',
    alertId: 'alt-003',
    issue: 'Rapid drop in Machine Health Indicator from 73 to 45 over 15 cycles',
    recommendedAction: 'Perform borescope inspection and check high-pressure turbine seal clearances.',
    decision: 'followed_recommendation',
    decisionRationale: 'Rapid sensor_11 thermal rise confirmed by trend facts; urgent teardown indicated.',
    actionTaken: 'Borescope inspection of stage 1 turbine blades and pressure sensor lead continuity check.',
    performedBy: 'engineer@demo.internal',
    performedAt: '2026-09-30 18:30:00 UTC',
    status: 'in_progress',
    outcome: 'unresolved',
    notes: 'Unit taken offline into Hangar Bay 2. Teardown ongoing.',
  },
  {
    id: 'maint-002',
    machineId: 'm-fd001-02',
    machineCode: 'FD001-ENG-002',
    alertId: 'alt-004',
    issue: 'Early degradation warning (failure prob 42%)',
    recommendedAction: 'Increase monitoring frequency and review recent operating settings.',
    decision: 'modified',
    decisionRationale: 'Operational priority permitted a quick sensor connector seating inspection.',
    actionTaken: 'Inspected sensor harness and cleaned optical pyrometer lens.',
    performedBy: 'engineer@demo.internal',
    performedAt: '2026-09-29 13:30:00 UTC',
    status: 'completed',
    outcome: 'no_issue_found',
    notes: 'No hardware anomaly discovered. Unit confirmed safe to proceed under elevated monitoring.',
  },
];

export const INITIAL_DATASETS: Dataset[] = [
  {
    id: 'ds-fd001-demo',
    name: 'NASA C-MAPSS FD001 — Standard Split',
    version: 'v1.0-standard',
    adapterKey: 'cmapss_fd001_csv',
    adapterVersion: '1.0.0',
    dataOrigin: 'simulated',
    isDemo: true,
    status: 'ingested',
    checksumSha256: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    rowCount: 20631,
    unitCount: 100,
    uploadedBy: 'system (seed)',
    uploadedAt: '2026-09-30 08:00:00 UTC',
  },
  {
    id: 'ds-ai4i-sample',
    name: 'AI4I 2020 Predictive Maintenance (Synthetic Tabular)',
    version: 'v1.0-rejected-demo',
    adapterKey: 'cmapss_fd001_csv',
    adapterVersion: '1.0.0',
    dataOrigin: 'synthetic',
    isDemo: true,
    status: 'rejected_incompatible',
    checksumSha256: '9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08',
    rowCount: 10000,
    unitCount: 1,
    uploadedBy: 'system (compatibility demo)',
    uploadedAt: '2026-09-30 08:05:00 UTC',
  },
];

export const INITIAL_MODELS: ModelVersion[] = [
  {
    id: 'mod-lgbm-01',
    name: 'FD001 Calibrated Failure Predictor',
    task: 'failure_risk',
    modelType: 'LightGBM Classifier + Sigmoid Calibrator',
    version: 'LightGBM-FD001-v1.2',
    adapterKey: 'cmapss_fd001_csv',
    status: 'active',
    horizon: 30,
    horizonUnit: 'cycles',
    decisionThreshold: 0.50,
    trainingDataset: 'NASA C-MAPSS FD001 Train (100 engines)',
    trainingDate: '2026-09-28',
    gitCommit: '9c4f18a',
    modelCard: {
      targetDefinition: 'Binary classification: failure within horizon H = 30 operating cycles (derived from RUL <= 30).',
      calibrationInfo: 'Platt scaling (sigmoid calibration) fitted strictly on held-out engine validation partition.',
      featuresUsed: ['sensor_2', 'sensor_3', 'sensor_4', 'sensor_7', 'sensor_8', 'sensor_9', 'sensor_11', 'sensor_12', 'sensor_13', 'sensor_14', 'sensor_15', 'sensor_17', 'sensor_20', 'sensor_21', 'rolling_mean_15', 'rolling_std_15', 'ewma_10', 'robust_z_deviation'],
      intendedUse: 'Decision-support failure likelihood forecasting on simulated turbofan engine time-series data.',
      limitations: 'Trained exclusively on NASA C-MAPSS FD001 simulated data. Not validated on real physical industrial rotating equipment. Requires contiguous cycle sequences.',
    },
  },
  {
    id: 'mod-iforest-01',
    name: 'FD001 Baseline Anomaly Detector',
    task: 'anomaly',
    modelType: 'Isolation Forest + Statistical Z-Score Baseline',
    version: 'IsolationForest-FD001-v1.0',
    adapterKey: 'cmapss_fd001_csv',
    status: 'active',
    horizon: null,
    horizonUnit: null,
    decisionThreshold: 0.65,
    trainingDataset: 'NASA C-MAPSS FD001 Healthy Window Baseline (first 30 cycles)',
    trainingDate: '2026-09-28',
    gitCommit: '9c4f18a',
    modelCard: {
      targetDefinition: 'Unsupervised anomaly score relative to initial healthy operating cycles.',
      calibrationInfo: 'Calibrated to 5% false-positive rate on held-out healthy engine slices.',
      featuresUsed: ['sensor_2', 'sensor_3', 'sensor_4', 'sensor_7', 'sensor_8', 'sensor_9', 'sensor_11', 'sensor_12', 'sensor_13', 'sensor_14', 'sensor_15', 'sensor_17', 'sensor_20', 'sensor_21'],
      intendedUse: 'Early drift and abnormal sequence identification prior to failure precursors.',
      limitations: 'Assumes first 30 cycles represent fault-free operational behavior.',
    },
  },
];

export const INITIAL_EVALUATION: ModelEvaluation = {
  modelId: 'mod-lgbm-01',
  modelVersion: 'LightGBM-FD001-v1.2',
  evaluatedAt: '2026-09-28 14:32:00 UTC',
  evaluationDataset: 'NASA C-MAPSS FD001 Test Set (100 engines with ground-truth RUL)',
  splitProtocol: 'GroupKFold by Engine ID (5-fold, zero engine leakage across splits)',
  metrics: {
    prAuc: 0.892,
    rocAuc: 0.946,
    precision: 0.854,
    recall: 0.887,
    f1Score: 0.870,
    brierScore: 0.081,
    baselinePrAuc: 0.320,
    baselineRocAuc: 0.830,
  },
  confusionMatrix: {
    tp: 182,
    fp: 31,
    fn: 23,
    tn: 684,
  },
  prCurve: [
    { recall: 0.0, precision: 1.0 },
    { recall: 0.2, precision: 0.98 },
    { recall: 0.4, precision: 0.95 },
    { recall: 0.6, precision: 0.92 },
    { recall: 0.75, precision: 0.89 },
    { recall: 0.88, precision: 0.85 },
    { recall: 0.94, precision: 0.76 },
    { recall: 1.0, precision: 0.32 },
  ],
  rocCurve: [
    { fpr: 0.0, tpr: 0.0 },
    { fpr: 0.02, tpr: 0.54 },
    { fpr: 0.04, tpr: 0.78 },
    { fpr: 0.08, tpr: 0.89 },
    { fpr: 0.12, tpr: 0.93 },
    { fpr: 0.20, tpr: 0.97 },
    { fpr: 1.0, tpr: 1.0 },
  ],
  calibrationCurve: [
    { meanPredictedValue: 0.05, fractionOfPositives: 0.04 },
    { meanPredictedValue: 0.15, fractionOfPositives: 0.14 },
    { meanPredictedValue: 0.30, fractionOfPositives: 0.29 },
    { meanPredictedValue: 0.50, fractionOfPositives: 0.52 },
    { meanPredictedValue: 0.70, fractionOfPositives: 0.69 },
    { meanPredictedValue: 0.85, fractionOfPositives: 0.87 },
    { meanPredictedValue: 0.95, fractionOfPositives: 0.96 },
  ],
  featureImportance: [
    { feature: 'sensor_11 (HPC Outlet Temp)', importance: 0.28 },
    { feature: 'sensor_9 (Core Speed)', importance: 0.21 },
    { feature: 'sensor_14 (Bypass Duct Temp)', importance: 0.16 },
    { feature: 'sensor_4 (LPT Outlet Temp)', importance: 0.13 },
    { feature: 'sensor_12 (Fan Speed)', importance: 0.09 },
    { feature: 'sensor_7 (HPT Coolant Bleed)', importance: 0.07 },
    { feature: 'sensor_2 (LPC Outlet Temp)', importance: 0.06 },
  ],
};

// Generates 60 cycles of sensor history for machine detail charts
export function generateSensorHistory(machineId: string, currentCycle: number): SensorReading[] {
  const readings: SensorReading[] = [];
  const startCycle = Math.max(1, currentCycle - 59);

  for (let c = startCycle; c <= currentCycle; c++) {
    const progress = c / currentCycle;
    const isLate = progress > 0.8;
    const isCritical = machineId === 'm-fd001-03';

    // Sensor 11: baseline ~ 47.1, rises toward 48.2 in degraded engines
    const base11 = 47.10 + (isCritical ? Math.pow(progress, 3) * 1.05 : progress * 0.4);
    const noise11 = (Math.sin(c * 0.4) * 0.04) + (Math.cos(c * 0.7) * 0.03);

    // Sensor 9: baseline ~ 9050, rises toward 9100
    const base9 = 9050 + (isCritical ? Math.pow(progress, 3) * 50 : progress * 20);
    const noise9 = (Math.sin(c * 0.3) * 3) + (Math.random() * 2);

    // Sensor 4: baseline ~ 1400, rises toward 1425
    const base4 = 1400 + (isCritical ? Math.pow(progress, 2.5) * 23 : progress * 8);

    // Sensor 12: baseline ~ 522, decreases slightly in degradation
    const base12 = 522 - (isCritical ? Math.pow(progress, 2) * 2.5 : progress * 0.8);

    readings.push({
      cycle: c,
      sensor_11: parseFloat((base11 + noise11).toFixed(2)),
      sensor_9: parseFloat((base9 + noise9).toFixed(1)),
      sensor_4: parseFloat((base4 + (Math.random() * 1.5)).toFixed(1)),
      sensor_12: parseFloat((base12 + (Math.random() * 0.4)).toFixed(2)),
      sensor_2: parseFloat((642.0 + Math.sin(c * 0.5) * 0.8).toFixed(2)),
      sensor_7: parseFloat((553.8 + Math.cos(c * 0.3) * 0.4).toFixed(2)),
      isAnomaly: isCritical && isLate,
      isImputed: c === currentCycle - 12 && machineId === 'm-fd001-05',
    });
  }

  return readings;
}
